### ISSUE TITLE
关于表格内字体大小的设置

### ISSUE THREAD

**Issue by lostcorner** [bjut-swift/BJUTLATEX#10]
表格内的中文字体应该为小五，应为字体为9磅，但是现在显示的应该都是正文的大小，该如何解决。

**Comment by gxyuu1999** [comment]
我问的gpt，这么写的。查格式机器人没查出来。

\begin{table}[htpb]
  \centering
  {\fontsize{9pt}{11pt}\selectfont % 设置文字大小为9磅
  \renewcommand{\arraystretch}{1.5} % 设置表格行高为6mm
  \setlength{\arrayrulewidth}{0.75pt} % 设置顶线和底线粗细为0.75pt
  \setlength{\abovetopsep}{0pt} % 设置顶线与内容的距离为0pt
  \setlength{\belowbottomsep}{0pt} % 设置底线与内容的距离为0pt
  \setlength{\heavyrulewidth}{0.75pt} % 设置顶线和底线粗细为0.75pt
  \setlength{\lightrulewidth}{0.5pt} % 设置中间栏目线粗细为0.5pt
  \setlength{\doublerulesep}{0pt} % 设置双线之间的距离为0pt
  \bicaption[]{}{}
  \label{tab:}
  \begin{tabular}{@{}cccc@{}}
    \toprule
    1 & 2 & 3 &4  \\
    \midrule
    1 & 2 & 3 &4  \\
    \bottomrule
  \end{tabular}
  }
\end{table}

**Comment by lostcorner** [comment]
我目前的解决方案如下，还没查过格式
```latex
\begin{table*}[htpb]
    \centering
    {
    \begingroup
    % \setlength{\tabcolsep}{10pt} % Default value: 6pt
    \renewcommand{\arraystretch}{1.5} % Default value: 1
    \footnotesize % fontsize 9pt
    \begin{tabular}{@{\hspace{2em}}c@{\hspace{5em}}c@{\hspace{2em}}}
    \toprule
    2 & 1 \\ 
    \midrule
    1 & 2 \\
    \bottomrule
    \end{tabular}
    \endgroup
    }
\end{table*}

```

**Comment by PEKEW** [comment]
本人提交毕业论文时，使用了\footnotesize 。
实际上表格的字体大小并不会影响格式检查结果。
如果追求视觉上的表格字体与word格式要求完全一致，需要自行调整。
