### ISSUE TITLE
关于参考文献的引用格式的问题。

### ISSUE THREAD

**Issue by VthuS** [bjut-swift/BJUTLATEX#2]
您好，非常感谢您的模板，为我毕业论文写作节省大量时间。
       但是我没有找到您在模板中有参考文献，我自己加了参考文献模板。但是由于Latex使用还不太熟练，所以不知道在使用\bibliographystyle{}时应该使用哪个格式。所以想请教您用的是哪个格式？希望借鉴一下您的格式。
       最后还是要感谢您的帮助，祝您顺利毕业！
       顺颂春祺。

**Comment by PEKEW** [comment]
谢谢，我的模版自定义了学位论文要求的国标格式，该文件为:`gbref.bst`。也就是说，并不需要要你手动指定`bibstyle`，你要做的只是在`reference.bib`文件中添加bibtex格式的参考文献即可。另外，我更新了最新版，请注意确保使用最新的模版。

**Comment by VthuS** [comment]
那请问我如何生成带参考文献的PDF版本的论文呢？

> 谢谢，我的模版自定义了学位论文要求的国标格式，该文件为:`gbref.bst`。也就是说，并必须要你手动指定`bibstyle`，你要做的只是在`reference.bib`文件中添加bibtex格式的参考文献即可。另外，我更新了最新版，请注意确保使用最新的模版。

**Comment by VthuS** [comment]
> 谢谢，我的模版自定义了学位论文要求的国标格式，该文件为:`gbref.bst`。也就是说，并必须要你手动指定`bibstyle`，你要做的只是在`reference.bib`文件中添加bibtex格式的参考文献即可。另外，我更新了最新版，请注意确保使用最新的模版。

我明白了，实在是感谢您

**Comment by PEKEW** [comment]
首先，你的参考文献应该以bibtex的格式组织在`reference.bib`的文件中，当然你可以命名为其他。然后，在你的`main.tex`中应该有`\makebib{reference}`。最后，你只需要正常编译`main.tex`文件即可。如图：
<img width="732" alt="image" src="https://user-images.githubusercontent.com/98371836/221397751-8d7aef3a-92e7-4a7f-8fa5-857e22af43b2.png">

**Comment by PEKEW** [comment]
> 

必须要 -> 不需要
