### ISSUE TITLE
\citen的修改建议

### ISSUE THREAD

**Issue by superciv** [bjut-swift/BJUTLATEX#5]
目前的\citen命令无法和正文对其，括号明显偏下（我也不知道为什么），显示效果：
<img width="404" alt="屏幕截图 2024-01-18 171551" src="https://github.com/PEKEW/BJUTLATEX/assets/29683798/e621fa36-b403-49fe-bfc3-b3e13e95b8a5">
可以考虑修改为：
`\newcommand{\citen}[1]{\hspace{0.15ex}\nocite{#1}\raisebox{0.3mm}{[}\kern-0.35em\citenum{#1}\kern-0.05em\raisebox{0.3mm}{]}\hspace{-0.03em}}`
显示效果正常：
<img width="422" alt="屏幕截图 2024-01-18 171800" src="https://github.com/PEKEW/BJUTLATEX/assets/29683798/a5d340fd-6fbe-49eb-a61a-2de5b7bb20ce">

**Comment by PEKEW** [comment]
感谢支持！我已经把这个解决方案放在了readme中说明。
