### ISSUE TITLE
关于模版中的中文字体设置

### ISSUE THREAD

**Issue by lostcorner** [bjut-swift/BJUTLATEX#6]
更新：
找到了全局文字的方法，但不知道是否正确，也不清楚是否会影响其他格式，麻烦帮我确认一下。
<img width="458" alt="image" src="https://github.com/bjut-swift/BJUTLATEX/assets/41581944/7c2fe0ab-162b-4dda-99af-32408f3acd06">

=========================

原有的bjutthesis.cls中做了windows字体的设置，但并没有生效。这是我在.tex中重新声明字体后的结果。
代码如下：
```
\begin{conclusion}

\setCJKfamilyfont{zhsong}{SimSun.ttc}
\setCJKfamilyfont{zhhei}{SimHei.ttf}
\newcommand{\zhsong}{\CJKfamily{zhsong}}  %中易宋体
\newcommand{\zhhei}{\CJKfamily{zhhei}}  %中易黑体


原有模版：

领域。欢迎使用北京工业大学硕士研究生学位LaTeX 论文模版（学术型硕士）。制作本模版的思路是因为Office for MacOS的体验极差，加之本人又对word十分不熟练。网上目前没有现成的模版给我白嫖，本着开源精神和拙劣的LaTeX 理解，参考部分模版（见致谢）赶工出该模版的版本。希望借助此模版，使用者能将本就在毕业季不多的精力专注于文字而不是行距、行高、段落等繁琐的格式上。接下来将介绍模版的使用方法。本模版中大量格式参考《北京工业大学研究生学位论文撰写规范》和北京工业大学博士论文LaTeX 模版（见致谢）。关于格式定制问题，欢迎issue 至此模版的git仓库。\uline{https://github.com/PEKEW/BJUTLATEX}

//===============

修改字体后：

{\zhsong 领域。欢迎使用北京工业大学硕士研究生学位LaTeX 论文模版（学术型硕士）。制作本模版的思路是因为Office for MacOS的体验极差，加之本人又对word十分不熟练。网上目前没有现成的模版给我白嫖，本着开源精神和拙劣的LaTeX 理解，参考部分模版（见致谢）赶工出该模版的版本。希望借助此模版，使用者能将本就在毕业季不多的精力专注于文字而不是行距、行高、段落等繁琐的格式上。接下来将介绍模版的使用方法。本模版中大量格式参考《北京工业大学研究生学位论文撰写规范》和北京工业大学博士论文LaTeX 模版（见致谢）。关于格式定制问题，欢迎issue 至此模版的git仓库。\uline{https://github.com/PEKEW/BJUTLATEX}}


\end{conclusion}

```
结果如下：
<img width="572" alt="image" src="https://github.com/bjut-swift/BJUTLATEX/assets/41581944/d02565db-27ef-4394-af78-e0cbda92d07b">

从“领域”两字和标点符号中可以看出两者字体不同。

请问怎样才能在.cls中全局设置字体。

**Comment by PEKEW** [comment]
你好，经过测试，原有的字体设置在 Windows 环境下是可以正常生效的，前提是你正确指定了 *.ttc / *.ttf 文件的位置，例如 SimSun.ttc。

其次，setCJKmainfont 的确是用于设置中日韩主要字体的命令（CJK），它的影响范围是整个文档的所有正文部分。一旦设置了 setCJKmainfont，整个文档的 CJK 部分都会使用指定的字体，除非你进行了单独的设置（这时可以使用 setCJKfamilyfont）。

**Comment by lostcorner** [comment]
你好，字体区别应该就是ctex在overleaf、Windows和macOS上字体版权的问题。
目前没有本地latex的环境，所以就继续在overleaf上撰写论文，但不知道对格式是否会有改动，等写完论文后我再对比一下。
