### ISSUE TITLE
目录行间距调整

### ISSUE THREAD

**Issue by superciv** [bjut-swift/BJUTLATEX#9]
根据最新下发的论文格式要求：“目录内容行距 1.3”，应该设置目录行间距为1.3倍word行间距。
目前bitoc.sty文件中`{\zihao{-4}\linespread{1.53}\selectfont\tableofcontents}\normalsize`设置的行间距过大，
应该调整为`{\zihao{-4}\linespread{1.42}\selectfont\tableofcontents}\normalsize`恰好与1.3倍word行间距对应。
我已对显示效果进行测试，如下图：
<img width="674" alt="word" src="https://github.com/bjut-swift/BJUTLATEX/assets/29683798/97ffb2b8-ae71-44bf-813a-d058f0829d0e">
<img width="391" alt="PDF" src="https://github.com/bjut-swift/BJUTLATEX/assets/29683798/bf659aef-2764-4e7e-b76f-a8f0d210c83f">
可以看到，word和pdf排版了一样多的内容，可以认为行间距设置正确。

**Comment by superciv** [comment]
还有正文的\linespread应调整为1而非1.08，我测试每页容纳的内容和1.3倍行间距的word相同

**Comment by PEKEW** [comment]
> 根据最新下发的论文格式要求：“目录内容行距 1.3”，应该设置目录行间距为1.3倍word行间距。 目前bitoc.sty文件中`{\zihao{-4}\linespread{1.53}\selectfont\tableofcontents}\normalsize`设置的行间距过大， 应该调整为`{\zihao{-4}\linespread{1.42}\selectfont\tableofcontents}\normalsize`恰好与1.3倍word行间距对应。 我已对显示效果进行测试，如下图： <img alt="word" width="674" src="https://private-user-images.githubusercontent.com/29683798/313121053-97ffb2b8-ae71-44bf-813a-d058f0829d0e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA4MjMxNjQsIm5iZiI6MTcxMDgyMjg2NCwicGF0aCI6Ii8yOTY4Mzc5OC8zMTMxMjEwNTMtOTdmZmIyYjgtYWU3MS00NGJmLTgxM2EtZDA1OGYwODI5ZDBlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzE5VDA0MzQyNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWFkMzFlNzA5NmRmZDIwZGM0Njc5MjMxYzY4ZGNiMzM1MTc5Y2U5YjkyYzMwYzk5ZmI3YjRhNGI2OGZlZWU0ZGMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Q_T_XXW5GNW9vEMf07KvIOvRTp14Z1GTyUH4o99ejzA"> <img alt="PDF" width="391" src="https://private-user-images.githubusercontent.com/29683798/313121075-bf659aef-2764-4e7e-b76f-a8f0d210c83f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA4MjMxNjQsIm5iZiI6MTcxMDgyMjg2NCwicGF0aCI6Ii8yOTY4Mzc5OC8zMTMxMjEwNzUtYmY2NTlhZWYtMjc2NC00ZTdlLWI3NmYtYThmMGQyMTBjODNmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzE5VDA0MzQyNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTYxZmM5NTAwMDgxNjcyZGE1ZmVmZTZhMGRjNWRlYjk5NWY1OWQxYzQyZDUyMDNhY2MwYzQwODc0NDc2NTY0ZDEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.UVUKZ1NxbqdDsCr_eFOhkqCmucmaAvYcItp6_Gs_5rA"> 可以看到，word和pdf排版了一样多的内容，可以认为行间距设置正确。

谢谢同学，能否提供该word文档导出为pdf文档的效果对比。

**Comment by superciv** [comment]
> 谢谢同学，能否提供该word文档导出为pdf文档的效果对比。

word导出pdf也是一样的。要不加个QQ？截图不好说，我给你文件。
请解码如下字符串 "MTYwMDIyMzg2MQ==" 搜索QQ。(Hint: Base64)
